Django_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('books.urls', namespace='books')),
]

handler404 = 'Django_final.views.handler404'
handler500 = 'Django_final.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView, TemplateView
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from books.views.normal_views import (
    HomeView,
    BookSearchView,
    BookDetailView,
    FilteredReservedBooksView,
    GenreListView,
    FilteredBorrowListView
)
from books.views.api_views import (
    BookListAPIView,
    AuthorDetailAPIView,
    AuthorListAPIView,
    GenreDetailAPIView,
    GenreListAPIView,
    BookDetailsAPIView,
    ReserveDetailView,
    BorrowDetailView,
    BorrowListAPIView,
    ReserveListAPIView,
    AuthorCreateView,
    GenreCreateView,
    BookCreateView,
    AuthorBatchCreateView,
    GenreBatchCreateView,
    BookBatchCreateView,
    BorrowCreateView,
    ReserveCreateView,
    CustomTokenObtainPairView,
    StatisticsTopBookListAPIView,
    StatisticsBookBorrowsListAPIView,
    StatisticsBookBorrowsLateBooksListAPIView,
    StatisticsBookBorrowsLateUsersListAPIView,
    BorrowDueView, ReserveDueView,
)

app_name = 'books'

urlpatterns = [
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', HomeView.as_view(), name='home'),
    path('search/', BookSearchView.as_view(), name='search'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('genres/', GenreListView.as_view(), name='genres'),

    path('borrow', FilteredBorrowListView.as_view(), name='borrow'),
    path('reserve', FilteredReservedBooksView.as_view(), name='reserve'),

    path('api/books/', BookListAPIView.as_view(), name='book-list'),
    path('api/authors/', AuthorListAPIView.as_view(), name='author-list'),
    path('api/genres/', GenreListAPIView.as_view(), name='genre-list'),
    path('api/borrows/', BorrowListAPIView.as_view(), name='borrow-list'),
    path('api/reserves/', ReserveListAPIView.as_view(), name='reserve-list'),

    path('api/books/<int:pk>/', BookDetailsAPIView.as_view(), name='book-detail'),
    path('api/authors/<int:pk>/', AuthorDetailAPIView.as_view(), name='author-detail'),
    path('api/genres/<int:pk>/', GenreDetailAPIView.as_view(), name='genre-detail'),
    path('api/reserves/<int:pk>/', ReserveDetailView.as_view(), name='reserve-detail'),
    path('api/borrows/<int:pk>/', BorrowDetailView.as_view(), name='borrow-detail'),

    path('api/authors/create/', AuthorCreateView.as_view(), name='author-create'),
    path('api/genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('api/books/create/', BookCreateView.as_view(), name='book-create'),
    path('api/borrows/create/', BorrowCreateView.as_view(), name='borrow-create'),
    path('api/reserves/create/', ReserveCreateView.as_view(), name='reserve-create'),

    path('api/authors/create_batch/', AuthorBatchCreateView.as_view(), name='author-create-batch'),
    path('api/genres/create_batch/', GenreBatchCreateView.as_view(), name='genre-create-batch'),
    path('api/books/create_batch/', BookBatchCreateView.as_view(), name='book-create-batch'),

    path('api/statistics/top-books/', StatisticsTopBookListAPIView.as_view(), name='top-books'),
    path('api/statistics/top-worst-users/', StatisticsBookBorrowsLateUsersListAPIView.as_view(), name='top-worst-users'),
    path('api/statistics/books_borrows/', StatisticsBookBorrowsListAPIView.as_view(), name='top-books-borrows'),
    path('api/statistics/late_returns', StatisticsBookBorrowsLateBooksListAPIView.as_view(), name='late-returns'),

    path('api/borrow_due', BorrowDueView.as_view(), name='borrow-due'),
    path('api/reserve_due', ReserveDueView.as_view(), name='reserve-due'),
]

users/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView, TemplateView
from users.views import register_view, login_view, logout_view, profile_view, profile_update, ChangePasswordView

app_name = 'users'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile_update/', profile_update, name='profile_update'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from users.managers import CustomUserManager
from users.choices import UserTypeChoices


# Create your models here.
class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    personal_number = models.CharField(max_length=11, verbose_name=_("Personal Number"), unique=True)
    birth_date = models.DateField(_("Birth Date"))
    user_type = models.IntegerField(choices=UserTypeChoices.choices, blank=True, null=True,
                                 verbose_name=_("User Type"), default='client')
    is_authorized = models.BooleanField(default=True if settings.DEBUG else False, verbose_name=_("Is Authorized"))

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['user_type', 'first_name', 'last_name', 'personal_number', 'birth_date']

    objects = CustomUserManager()

    def __str__(self):
        return " ".join([self.first_name, self.last_name])

    def is_librarian(self):
        return self.user_type == 'librarian'

    def is_client(self):
        return self.user_type == 'client'

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

users/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import CustomUser
from users.validators import validate_personal_number
from users.choices import UserTypeChoicesForm, UserTypeChoices


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    personal_number = forms.CharField(max_length=11, validators=[validate_personal_number])
    birth_date = forms.DateField()
    # user_type = forms.ChoiceField(choices=UserTypeChoicesForm.choices,)

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password-input'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    # Add a field for password strength
    password_strength = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,
    )

    class Meta:
        model = CustomUser
        fields = ("email", 'first_name', 'last_name', 'birth_date', 'personal_number')

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.user_type = UserTypeChoices.STUDENT
        if commit:
            user.save()
        return user


class CustomUserChangeForm(UserChangeForm):
    personal_number = forms.IntegerField(validators=[validate_personal_number])
    user_type = forms.ChoiceField(choices=UserTypeChoicesForm.choices,
                                  widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ("email", 'first_name', 'last_name', 'birth_date', 'personal_number', 'user_type')
        exclude = ('password',)

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        # Remove the password field
        # if 'password' in self.fields:
        #     self.fields.pop('password')

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

class LoginForm(forms.Form):
    email = forms.CharField(
        label='Email',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password-input'}),
    )

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

class CustomUserCreationFormAdmin(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    personal_number = forms.CharField(max_length=11, validators=[validate_personal_number])
    birth_date = forms.DateField()
    user_type = forms.ChoiceField(choices=UserTypeChoices.choices,)

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password-input'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    # Add a field for password strength
    password_strength = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,
    )

    class Meta:
        model = CustomUser
        fields = ("email", 'first_name', 'last_name', 'birth_date', 'personal_number', 'user_type')


class CustomUserChangeFormAdmin(UserChangeForm):
    personal_number = forms.IntegerField(validators=[validate_personal_number])
    user_type = forms.ChoiceField(choices=UserTypeChoices.choices,
                                  widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ("email", 'first_name', 'last_name', 'birth_date', 'personal_number', 'user_type')
        exclude = ('password',)

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeFormAdmin, self).__init__(*args, **kwargs)
        # Remove the password field
        # if 'password' in self.fields:
        #     self.fields.pop('password')

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from books.forms import BookForm
from users.choices import UserTypeChoices
from users.models import CustomUser
from users.forms import CustomUserCreationForm, LoginForm, CustomUserChangeForm
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy


# Create your views here.

def register_view(request):
    if request.method == 'POST':
        # Create a form that has request.POST
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # Set the user's password securely
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            if password1 == password2:
                user.set_password(password1)
                user.save()

                messages.success(request, f'Your Account has been created {email} ! Proceed to log in')
                login(request, user)
                return redirect('users:profile')
            else:
                # Handle password mismatch error here
                form.add_error('password2', 'Passwords entered do not match')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})


def login_view(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user:
                login(request, user)
                print(user.user_type)
                if user.user_type not in [UserTypeChoices.LIBRARIAN, UserTypeChoices.ADMIN]:
                    return redirect('users:profile')
                else:
                    return redirect('/admin/')
            else:
                form.add_error(field=None, error="Invalid username or password")

    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('users:login')


@login_required
def profile_view(request):
    form = BookForm()
    return render(request, 'users/profile.html', {'form': form})


@login_required
def profile_update(request):
    form = CustomUserChangeForm(instance=request.user)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully')
            return redirect('users:profile')
    return render(request, 'users/profile_update.html', {'form': form})


class ChangePasswordView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/change_password.html'

users/templates/users/change_password.html
{% extends 'base.html' %}

{% block title %}Change Password{% endblock %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
  </form>
    <br> <a href="{% url 'users:profile' %}">Back to Profile</a>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}
    {% block content %}
    <div class="login-card">
        <h2>Login</h2>
        <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>

    <br>
    <button>
        <a href="{% url 'users:register' %}">Register</a>
    </button>

    </div>
    {% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}
{%  block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}
{% block content %}
        {% if messages %}
        <div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    {% include 'header.html' %}
    <h1>Profile</h1>
    <p>Hi, {{ request.user }}</p>
    <p>Email: {{ request.user.email }}</p>
    <p>First Name: {{ request.user.first_name }}</p>
    <p>Last Name: {{ request.user.last_name }}</p>
    <p>Personal Number: {{ request.user.personal_number }}</p>

    <h2>Borrowed Books</h2>
        <ul>
            <li><a href="{% url 'books:not_due_books' %}">Borrowed Books Not Due</a></li>
            <li><a href="{% url 'books:due_books' %}">Borrowed Books Due</a></li>
            <li><a href="{% url 'books:borrow_history' %}">Borrow History</a></li>
        </ul>

    <h2>Reserved Books</h2>
        <ul>
            <li><a href="{% url 'books:active_reserved_books' %}">Active Reserved Books</a></li>
            <li><a href="{% url 'books:reserved_books_history' %}">Reserved Books History</a></li>
        </ul>

    <h2>Update Profile</h2>
    <ul>
    <li> <a href="{% url 'users:profile_update' %}">Update Profile</a> </li>
    <li> <a href="{% url 'users:change_password' %}">Update Password</a> </li>
        <br>
    <li> <a href="{% url 'users:logout' %}">Logout</a> </li>
</ul>
{%  endblock %}

users/templates/users/profile_update.html
{% extends 'base.html' %}

{% block title %}Update Profile{% endblock %}
{% block content %}
    <div class="form-card">
        <h2>Update Profile</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>

    <br> <a href="{% url 'users:profile' %}">Back to Profile</a>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}
    {% block content %}
    <div class="form-card">
        <h2>Sign Up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign Up</button>
        </form>
    </div>
    {% endblock %}