Django_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('books.urls', namespace='books')),
]

handler404 = 'Django_final.views.handler404'
handler500 = 'Django_final.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView, TemplateView
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from books.views.normal_views import (
    HomeView,
    BookSearchView,
    BookDetailView,
    FilteredReservedBooksView,
    GenreListView,
    FilteredBorrowListView
)
from books.views.api_views import (
    BookListAPIView,
    AuthorDetailAPIView,
    AuthorListAPIView,
    GenreDetailAPIView,
    GenreListAPIView,
    BookDetailsAPIView,
    ReserveDetailView,
    BorrowDetailView,
    BorrowListAPIView,
    ReserveListAPIView,
    AuthorCreateView,
    GenreCreateView,
    BookCreateView,
    AuthorBatchCreateView,
    GenreBatchCreateView,
    BookBatchCreateView,
    BorrowCreateView,
    ReserveCreateView,
    CustomTokenObtainPairView,
    StatisticsTopBookListAPIView,
    StatisticsBookBorrowsListAPIView,
    StatisticsBookBorrowsLateBooksListAPIView,
    StatisticsBookBorrowsLateUsersListAPIView,
    BorrowDueView, ReserveDueView,
)

app_name = 'books'

urlpatterns = [
    path('api/token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', HomeView.as_view(), name='home'),
    path('search/', BookSearchView.as_view(), name='search'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('genres/', GenreListView.as_view(), name='genres'),

    path('borrow', FilteredBorrowListView.as_view(), name='borrow'),
    path('reserve', FilteredReservedBooksView.as_view(), name='reserve'),

    path('api/books/', BookListAPIView.as_view(), name='book-list'),
    path('api/authors/', AuthorListAPIView.as_view(), name='author-list'),
    path('api/genres/', GenreListAPIView.as_view(), name='genre-list'),
    path('api/borrows/', BorrowListAPIView.as_view(), name='borrow-list'),
    path('api/reserves/', ReserveListAPIView.as_view(), name='reserve-list'),

    path('api/books/<int:pk>/', BookDetailsAPIView.as_view(), name='book-detail'),
    path('api/authors/<int:pk>/', AuthorDetailAPIView.as_view(), name='author-detail'),
    path('api/genres/<int:pk>/', GenreDetailAPIView.as_view(), name='genre-detail'),
    path('api/reserves/<int:pk>/', ReserveDetailView.as_view(), name='reserve-detail'),
    path('api/borrows/<int:pk>/', BorrowDetailView.as_view(), name='borrow-detail'),

    path('api/authors/create/', AuthorCreateView.as_view(), name='author-create'),
    path('api/genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('api/books/create/', BookCreateView.as_view(), name='book-create'),
    path('api/borrows/create/', BorrowCreateView.as_view(), name='borrow-create'),
    path('api/reserves/create/', ReserveCreateView.as_view(), name='reserve-create'),

    path('api/authors/create_batch/', AuthorBatchCreateView.as_view(), name='author-create-batch'),
    path('api/genres/create_batch/', GenreBatchCreateView.as_view(), name='genre-create-batch'),
    path('api/books/create_batch/', BookBatchCreateView.as_view(), name='book-create-batch'),

    path('api/statistics/top-books/', StatisticsTopBookListAPIView.as_view(), name='top-books'),
    path('api/statistics/top-worst-users/', StatisticsBookBorrowsLateUsersListAPIView.as_view(), name='top-worst-users'),
    path('api/statistics/books_borrows/', StatisticsBookBorrowsListAPIView.as_view(), name='top-books-borrows'),
    path('api/statistics/late_returns', StatisticsBookBorrowsLateBooksListAPIView.as_view(), name='late-returns'),

    path('api/borrow_due', BorrowDueView.as_view(), name='borrow-due'),
    path('api/reserve_due', ReserveDueView.as_view(), name='reserve-due'),
]

books/forms.py
from django import forms
from django.conf import settings
from django.utils import timezone

from books.models import Borrow, Reserve


class BookForm(forms.Form):
    query = forms.CharField(label='Search books',
                            required=False,
                            widget=forms.TextInput(attrs={'placeholder': 'Search books...'}))

class GenreForm(forms.Form):
    genre = forms.CharField(label='Search genres',
                            required=False,
                            widget=forms.TextInput(attrs={'placeholder': 'Search genres...'}))

class BorrowAdminForm(forms.ModelForm):
    class Meta:
        model = Borrow
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        due_date = cleaned_data.get("due_date")
        if not due_date:
            cleaned_data["due_date"] = timezone.now() + settings.BORROW_TIME_LIMIT
        return cleaned_data


class ReserveAdminForm(forms.ModelForm):
    class Meta:
        model = Reserve
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        due_date = cleaned_data.get("due_date")
        if not due_date:
            cleaned_data["due_date"] = timezone.now() + settings.RESERVE_TIME_LIMIT
        return cleaned_data

books/views/api_views.py
from datetime import timedelta
import json

from django.db import transaction
from django.db.models import Count, Case, When, IntegerField, F, Q
from django.http import JsonResponse
from django.utils import timezone
from django.views.generic import View
from rest_framework import generics, permissions, status
from rest_framework.authentication import SessionAuthentication
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework_simplejwt.views import TokenObtainPairView



from Django_final.emailing import email_borrow, email_reserve
from books.choices import filter_conditions
from books.models import Author, Genre, Book, Borrow, Reserve
from books.paginators import CustomPageNumberPagination
from books.serializers import (BookSerializer,
                               AuthorSerializer,
                               GenreSerializer,
                               AuthorDetailsSerializer,
                               GenreDetailsSerializer,
                               ReserveStatusUpdateSerializer,
                               ReserveSerializer,
                               BorrowStatusUpdateSerializer,
                               BorrowSerializer,
                               CreateBookSerializer,
                               BorrowCreateSerializer,
                               ReserveCreateSerializer, CustomTokenObtainPairSerializer, TopBookSerializer,
                               TopWorstUserSerializer, CustomBorrowSerializer, CustomReserveSerializer,
                               )
from books.view_permissions import CreatePermissions, IsSystemUser
from users.choices import UserTypeChoices
from users.models import CustomUser


class AtomicCreateAPIView(generics.CreateAPIView):
    permission_classes = [CreatePermissions]
    authentication_classes = [SessionAuthentication, JWTAuthentication]

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer


class AtomicRetrieveUpdateAPIView(generics.RetrieveUpdateAPIView):
    permission_classes = [CreatePermissions]
    authentication_classes = [SessionAuthentication, JWTAuthentication]

    @transaction.atomic
    def put(self, request, *args, **kwargs):
        return super().put(request, *args, **kwargs)

    @transaction.atomic
    def patch(self, request, *args, **kwargs):
        return super().patch(request, *args, **kwargs)


class AuthListAPIView(generics.ListAPIView):
    permission_classes = [CreatePermissions]
    authentication_classes = [SessionAuthentication, JWTAuthentication]

    filter_conditions = filter_conditions

    def apply_filters(self, queryset):
        filters = self.request.query_params.get('filters', '[]')
        late = self.request.query_params.get('late', None)

        try:
            filters = json.loads(filters)
        except json.JSONDecodeError:
            filters = []

        if late and json.loads(late.lower()):
            queryset = queryset.filter(due_date__lt=F('returned_at'))

        for filter in filters:
            field = filter.get('field')
            value = filter.get('value')
            sub_field = filter.get('sub_field', '')
            condition = filter.get('condition', 'exact')
            condition = self.filter_conditions.get(condition, '__exact')

            if not field or value is None:
                continue

            if isinstance(value, str) and value.lower() in ['true', 'false']:
                value = value.lower() == 'true'

            if sub_field:
                filter_expression = f"{field}__{sub_field}{condition}"
            else:
                filter_expression = f"{field}{condition}"

            queryset = queryset.filter(**{filter_expression: value})

        queryset = queryset.order_by('id')
        return queryset


class AuthorCreateView(AtomicCreateAPIView):
    serializer_class = AuthorSerializer
    queryset = Author.objects.all()


class GenreCreateView(AtomicCreateAPIView):
    serializer_class = GenreSerializer
    queryset = Genre.objects.all()


class BookCreateView(AtomicCreateAPIView):
    serializer_class = CreateBookSerializer
    queryset = Book.objects.all()


class AuthorBatchCreateView(AtomicCreateAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data, many=isinstance(request.data, list))
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class GenreBatchCreateView(AtomicCreateAPIView):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer


    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data, many=isinstance(request.data, list))
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class BookBatchCreateView(AtomicCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = CreateBookSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data, many=isinstance(request.data, list))
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


class BookListAPIView(AuthListAPIView):
    serializer_class = BookSerializer
    pagination_class = CustomPageNumberPagination

    def get_queryset(self):
        queryset = Book.objects.prefetch_related(
            'authors',
            'genres',
            'borrows',
            'reserves'
        ).annotate(
            borrows_count=Count(
                Case(
                    When(borrows__returned=False, then=1),
                    output_field=IntegerField()
                )
            ),
            reserves_count=Count(
                Case(
                    When(reserves__status=True, then=1),
                    output_field=IntegerField()
                )
            )
        )

        queryset = self.apply_filters(queryset)
        queryset.order_by('id')
        return queryset


class BookDetailsAPIView(AtomicRetrieveUpdateAPIView):
    queryset = Book.objects.prefetch_related(
        'authors',
        'genres',
        'borrows',
        'reserves'
    ).annotate(
        borrows_count=Count(
            Case(
                When(borrows__returned=False, then=1),
                output_field=IntegerField()
            )
        ),
        reserves_count=Count(
            Case(
                When(reserves__status=True, then=1),
                output_field=IntegerField()
            )
        )
    )
    serializer_class = BookSerializer


class AuthorListAPIView(AuthListAPIView):
    serializer_class = AuthorSerializer
    pagination_class = CustomPageNumberPagination
    queryset = Author.objects.all().order_by('id')


class AuthorDetailAPIView(AtomicRetrieveUpdateAPIView):
    queryset = Author.objects.prefetch_related('books').annotate(books_count=Count('books'))
    serializer_class = AuthorDetailsSerializer


class GenreListAPIView(AuthListAPIView):
    serializer_class = GenreSerializer
    pagination_class = CustomPageNumberPagination
    queryset = Genre.objects.all().order_by('id')


class GenreDetailAPIView(AtomicRetrieveUpdateAPIView):
    queryset = Genre.objects.prefetch_related('books').annotate(books_count=Count('books'))
    serializer_class = GenreDetailsSerializer


class ReserveDetailView(AtomicRetrieveUpdateAPIView):
    queryset = Reserve.objects.all().order_by('id')

    def get_serializer_class(self):
        if self.request.method in ['PATCH', 'PUT']:
            return ReserveStatusUpdateSerializer
        return ReserveSerializer


class BorrowDetailView(AtomicRetrieveUpdateAPIView):
    queryset = Borrow.objects.all()

    def get_serializer_class(self):
        if self.request.method in ['PATCH', 'PUT']:
            return BorrowStatusUpdateSerializer
        return BorrowSerializer


class BorrowListAPIView(AuthListAPIView):
    serializer_class = BorrowSerializer
    pagination_class = CustomPageNumberPagination

    def get_queryset(self):
        queryset = Borrow.objects.all().prefetch_related('user', 'book')
        if self.request.user.user_type == str(UserTypeChoices.STUDENT):
            queryset = queryset.filter(user=self.request.user)

        queryset = self.apply_filters(queryset)

        queryset = queryset.order_by('due_date')
        return queryset


class ReserveListAPIView(AuthListAPIView):
    serializer_class = ReserveSerializer
    pagination_class = CustomPageNumberPagination
    ordering_fields = ['due_date']
    ordering = ['-due_date']

    def get_queryset(self):
        queryset = Reserve.objects.all().prefetch_related('user', 'book')
        if self.request.user.user_type == str(UserTypeChoices.STUDENT):
            queryset = queryset.filter(user=self.request.user)

        queryset = self.apply_filters(queryset)

        queryset = queryset.order_by('due_date')
        return queryset


class BorrowCreateView(AtomicCreateAPIView):
    queryset = Borrow.objects.all()
    serializer_class = BorrowCreateSerializer

    def create(self, request, *args, **kwargs):
        user = request.data.get('user')
        book = request.data.get('book')

        active_borrow = Borrow.objects.filter(user=user, book=book, returned=False).first()

        if active_borrow:
            return Response({"error": "There is already an active borrow on this book."},

books/templates/books/book.html
{% extends 'base.html' %}
{% block content %}
    {% include 'header.html' %}
  <div>
    <h1>{{ book.title }}</h1>
    <p>Authors: {{ book.authors.all|join:", " }}</p>
    <p>Genres: {{ book.genres.all|join:", " }}</p>
    <p>Release Date: {{ book.release_date }}</p>
    <p>Stock: {{ book.stock }}</p>
    <p>Borrows Count: {{ borrows_count }}</p>
    <p>Reserves Count: {{ reserves_count }}</p>
    <p>Available to Borrow: {% if available_to_borrow %}Yes{% else %}No{% endif %}</p>

    {% if user_reserved_book %}
      <p>This book is already reserved by you.</p>
        <form action="{% url 'books:book_detail' book.pk %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="reserve_cancel_form">
            <button type="submit">Cancel Reserve</button>
        </form>
    {% elif available_to_borrow %}
        <form action="{% url 'books:book_detail' book.pk %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_type" value="reserve_form">
            <button type="submit">Reserve</button>
        </form>
    {% else %}
      <p>This book is not available for borrowing.</p>
    {% endif %}
  </div>
{% endblock %}

books/templates/books/book_list.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    {% include 'header.html' %}
    <h1>Books</h1>
    <ul>
        {% for borrow in books %}

            <li><a href="{% url 'books:book_detail' borrow.book.pk %}">{{ borrow.book.title }}</a> - Due Date: {{ borrow.due_date }}</li>
        {% endfor %}
    </ul>

{% if books.has_other_pages %}
    <h2>Pages</h2>
    <ul>
        {% if books.has_previous %}
            <li><a href="?page=1">First</a></li>
            <li><a href="?page={{ books.previous_page_number }}">Previous</a></li>
        {% endif %}
    
        
        {% if prev_pages %}
            {% for prev_page in prev_pages %}
                <li><a href="?page={{ prev_page }}">{{ prev_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        <li class="active"><span>{{ books.number }}</span></li>
        
        {% if next_pages %}
            {% for next_page in next_pages %}
                <li><a href="?page={{ next_page }}">{{ next_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        {% if books.has_next %}
            <li><a href="?page={{ books.next_page_number }}">Next</a></li>
            <li><a href="?page={{ books.paginator.num_pages }}">Last</a></li>
        {% endif %}
    </ul>
{% endif %}
{% endblock %}

books/templates/books/books.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% include 'header.html' %}
    <h1>Books</h1>
    {% for book in books %}
        <div>
            <ul class="book-list">
                <li><a href="{% url 'books:book_detail' book.pk %}">{{ book.title }}</a></li>
            </ul>
        </div>
    {% endfor %}

{% if books.has_other_pages %}
    <h2>Pages</h2>
    <ul>
        {% if books.has_previous %}
            <li><a href="?page=1">First</a></li>
            <li><a href="?page={{ books.previous_page_number }}">Previous</a></li>
        {% endif %}
    
        
        {% if prev_pages %}
            {% for prev_page in prev_pages %}
                <li><a href="?page={{ prev_page }}">{{ prev_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        <li class="active"><span>{{ books.number }}</span></li>
        
        {% if next_pages %}
            {% for next_page in next_pages %}
                <li><a href="?page={{ next_page }}">{{ next_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        {% if books.has_next %}
            <li><a href="?page={{ books.next_page_number }}">Next</a></li>
            <li><a href="?page={{ books.paginator.num_pages }}">Last</a></li>
        {% endif %}
    </ul>
{% endif %}
{% endblock %}

books/templates/books/genres.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    {% include 'header.html' %}
    <h1>Genres</h1>
    
    <form method="GET" action="{% url 'books:genres' %}">
        <input type="text" name="query" placeholder="Search for genres" value="{{ query }}">
        <button type="submit">Search</button>
    </form>
    
  <ul>
    {% for book in books %}
      <li><a href="{% url 'books:search' %}?genre={{ book.id }}">{{ book.name }}</a></li>
    {% endfor %}
  </ul>

{% if books.has_other_pages %}
    <h2>Pages</h2>
    <ul>
        {% if books.has_previous %}
            <li><a href="?page=1">First</a></li>
            <li><a href="?page={{ books.previous_page_number }}">Previous</a></li>
        {% endif %}
    
        
        {% if prev_pages %}
            {% for prev_page in prev_pages %}
                <li><a href="?page={{ prev_page }}">{{ prev_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        <li class="active"><span>{{ books.number }}</span></li>
        
        {% if next_pages %}
            {% for next_page in next_pages %}
                <li><a href="?page={{ next_page }}">{{ next_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        {% if books.has_next %}
            <li><a href="?page={{ books.next_page_number }}">Next</a></li>
            <li><a href="?page={{ books.paginator.num_pages }}">Last</a></li>
        {% endif %}
    </ul>
{% endif %}
{% endblock %}

books/templates/books/home.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    {% include 'header.html' %}
    <h1>Books</h1>
    {% for book in books %}
        <div>
            <ul class="book-list">
                <li><a href="{% url 'books:book_detail' book.pk %}">{{ book.title }}</a></li>
            </ul>
        </div>
    {% endfor %}

{% if books.has_other_pages %}
    <h2>Pages</h2>
    <ul>
        {% if books.has_previous %}
            <li><a href="?page=1">First</a></li>
            <li><a href="?page={{ books.previous_page_number }}">Previous</a></li>
        {% endif %}
    
        
        {% if prev_pages %}
            {% for prev_page in prev_pages %}
                <li><a href="?page={{ prev_page }}">{{ prev_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        <li class="active"><span>{{ books.number }}</span></li>
        
        {% if next_pages %}
            {% for next_page in next_pages %}
                <li><a href="?page={{ next_page }}">{{ next_page }}</a></li>
            {% endfor %}
        {% endif %}
        
        {% if books.has_next %}
            <li><a href="?page={{ books.next_page_number }}">Next</a></li>
            <li><a href="?page={{ books.paginator.num_pages }}">Last</a></li>
        {% endif %}
    </ul>
{% endif %}
{% endblock %}